In [49]:
import pandas as pd 
import numpy as np 
import data_profiling
from data_profiling import ProfileReport
from IPython.display import display

1 - load and look at your data
2 - handle duplicates, missing values, messy columns
3 - run integrity checks

In [50]:
#load and look at the data
df = pd.read_csv("messy_sales_data.csv")
df

,Customer ID,Full Name,email,Signup_Date,country,Age,OrderDate,Product Category,Price,quantity,Payment Method,Rating
0,19,Maria Khan,maria.khan@example.com,14/12/2023,India,21.0,22-Apr-2023,Clothin,NaN,3.0,paypal,2.9
1,3,Lucas Wang,lucas.wang@example.com,"June 13, 2023",USA,35.0,03/08/2024,Home & Garden,$142.55,4.0,Debit Card,1.4
2,21,LIAM JOHNSON,LIAM.JOHNSON@EXAMPLE.COM,05/07/2024,Australia,999.0,07/08/2023,Sports,$451.71,3.0,debit card,1.0
3,28,Liam Nakamura,LIAM.NAKAMURA@EXAMPLE.COM,"July 10, 2024",United Kingdom,36.0,11/06/2023,unknown,$492.01,9.0,Credit Card,NaN
4,46,Chloe Dubois,chloe.dubois@example.com,09/19/2024,Australia,66.0,31/05/2024,Sports,-$416.13,9.0,Bank Transfer,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...
63,15,Fatima Ali,fatima.ali@example.com,2024-06-24,France,-28.0,"September 13, 2024",Sports,$482.36,9.0,PayPal,3.9
64,58,Olivia Smith,olivia.smith@example.com,"April 19, 2023",Australia,44.0,03/19/2024,Home & Garden,$319.61,8.0,CREDIT CARD,12.0
65,24,David Johnson,david.johnson@example.com,24/03/2023,Japan,21.0,10-Jul-2023,Electronics,$339.23,4.0,debit card,1.5
66,26,EMMA DUBOIS,emma.dubois@example.com,02/10/2024,France,33.0,15/05/2023,Toys,$324.52,8.0,Debit Card,4.7
67,48,Noah Patel,noah.patel@example.com,"November 24, 2023",Brazil,35.0,07/07/2024,electronics,$194.60,3.0,PayPal,1.3

In [51]:
profile = ProfileReport(df, title="Profile sales data", explorative=True)
profile.to_file("report.html")

100%|██████████| 12/12 [00:00<00:00, 1721.62it/s]00:00, 26.16it/s, Describe variable: Rating]
Summarize dataset: 100%|██████████| 38/38 [00:01<00:00, 27.79it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.22s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00, 13.85it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 301.03it/s]

In [52]:
print("******** Shape ********")
print(df.shape)

print("\n******** Dtypes ********")
print(df.dtypes)

print("\n******** Missing Values ********")
print(df.isnull().sum())

print("\n******** Head ********")
display(df.head())

print("\n******** Tail ********")
display(df.tail())

******** Shape ********
(68, 12)

******** Dtypes ********
Customer ID           int64
 Full Name           object
email                object
Signup_Date          object
country              object
Age                 float64
OrderDate            object
Product Category     object
Price                object
quantity            float64
Payment Method       object
Rating              float64
dtype: object

******** Missing Values ********
Customer ID         0
 Full Name          0
email               0
Signup_Date         0
country             5
Age                 6
OrderDate           0
Product Category    2
Price               3
quantity            2
Payment Method      3
Rating              5
dtype: int64

******** Head ********

,Customer ID,Full Name,email,Signup_Date,country,Age,OrderDate,Product Category,Price,quantity,Payment Method,Rating
0,19,Maria Khan,maria.khan@example.com,14/12/2023,India,21.0,22-Apr-2023,Clothin,NaN,3.0,paypal,2.9
1,3,Lucas Wang,lucas.wang@example.com,"June 13, 2023",USA,35.0,03/08/2024,Home & Garden,$142.55,4.0,Debit Card,1.4
2,21,LIAM JOHNSON,LIAM.JOHNSON@EXAMPLE.COM,05/07/2024,Australia,999.0,07/08/2023,Sports,$451.71,3.0,debit card,1.0
3,28,Liam Nakamura,LIAM.NAKAMURA@EXAMPLE.COM,"July 10, 2024",United Kingdom,36.0,11/06/2023,unknown,$492.01,9.0,Credit Card,NaN
4,46,Chloe Dubois,chloe.dubois@example.com,09/19/2024,Australia,66.0,31/05/2024,Sports,-$416.13,9.0,Bank Transfer,4.6

******** Tail ********

,Customer ID,Full Name,email,Signup_Date,country,Age,OrderDate,Product Category,Price,quantity,Payment Method,Rating
63,15,Fatima Ali,fatima.ali@example.com,2024-06-24,France,-28.0,"September 13, 2024",Sports,$482.36,9.0,PayPal,3.9
64,58,Olivia Smith,olivia.smith@example.com,"April 19, 2023",Australia,44.0,03/19/2024,Home & Garden,$319.61,8.0,CREDIT CARD,12.0
65,24,David Johnson,david.johnson@example.com,24/03/2023,Japan,21.0,10-Jul-2023,Electronics,$339.23,4.0,debit card,1.5
66,26,EMMA DUBOIS,emma.dubois@example.com,02/10/2024,France,33.0,15/05/2023,Toys,$324.52,8.0,Debit Card,4.7
67,48,Noah Patel,noah.patel@example.com,"November 24, 2023",Brazil,35.0,07/07/2024,electronics,$194.60,3.0,PayPal,1.3

In [53]:
#standardize column names
df.columns=(df.columns
            .str.replace(' ', '')
            .str.strip()
            .str.lower()
            )
df.columns

Index(['customerid', 'fullname', 'email', 'signup_date', 'country', 'age',
       'orderdate', 'productcategory', 'price', 'quantity', 'paymentmethod',
       'rating'],
      dtype='object')

In [54]:
#adjust col names
column_map = {
    'customerid': 'customer_id',
    'orderdate': 'order_date',
    'productcategory': 'product_category',
    'paymentmethod': 'payment_method',
}

df = df.rename(columns=column_map)
df.columns

Index(['customer_id', 'fullname', 'email', 'signup_date', 'country', 'age',
       'order_date', 'product_category', 'price', 'quantity', 'payment_method',
       'rating'],
      dtype='object')

In [55]:
# % of missing values
missing = df.isnull().mean()*100
print(missing[missing>0].sort_values(ascending=False))

age                 8.823529
country             7.352941
rating              7.352941
price               4.411765
payment_method      4.411765
product_category    2.941176
quantity            2.941176
dtype: float64

In [56]:
# duplicate count -> separate them or remove
n_dupes = df.duplicated().sum()
n_dupes

np.int64(5)

In [57]:
# how the dupes look like
df[df.duplicated(keep=False)].sort_values(by=list(df.columns))

,customer_id,fullname,email,signup_date,country,age,order_date,product_category,price,quantity,payment_method,rating
1,3,Lucas Wang,lucas.wang@example.com,"June 13, 2023",USA,35.0,03/08/2024,Home & Garden,$142.55,4.0,Debit Card,1.4
35,3,Lucas Wang,lucas.wang@example.com,"June 13, 2023",USA,35.0,03/08/2024,Home & Garden,$142.55,4.0,Debit Card,1.4
19,40,Olivia Kowalski,olivia.kowalski@example.com,2024-07-21,France,62.0,"May 11, 2023",Clothing,470.48,3.0,paypal,2.6
55,40,Olivia Kowalski,olivia.kowalski@example.com,2024-07-21,France,62.0,"May 11, 2023",Clothing,470.48,3.0,paypal,2.6
21,42,Emma Lopez,EMMA.LOPEZ@EXAMPLE.COM,18-Oct-2023,United Kingdom,999.0,2024-06-11,Toys,$318.31,6.0,credit card,NaN
56,42,Emma Lopez,EMMA.LOPEZ@EXAMPLE.COM,18-Oct-2023,United Kingdom,999.0,2024-06-11,Toys,$318.31,6.0,credit card,NaN
39,49,Priya Dubois,PRIYA.DUBOIS@EXAMPLE.COM,01/03/2024,Australia,52.0,05-Mar-2023,Clothing,$197.79,10.0,Credit Card,4.4
52,49,Priya Dubois,PRIYA.DUBOIS@EXAMPLE.COM,01/03/2024,Australia,52.0,05-Mar-2023,Clothing,$197.79,10.0,Credit Card,4.4
7,51,Sofia Ibrahim,sofia.ibrahim@example.com,06/19/2023,NaN,49.0,23/04/2024,Clothing,$269.39,7.0,Credit Card,1.3
45,51,Sofia Ibrahim,sofia.ibrahim@example.com,06/19/2023,NaN,49.0,23/04/2024,Clothing,$269.39,7.0,Credit Card,1.3

In [58]:
df = df.drop_duplicates()
df.shape

(63, 12)

In [59]:
# mssing values - numeric replace with median, categorical replace with Unkown

df = df.copy()

# numeric
for col in df.select_dtypes(include="number").columns:
    # if there's a col you don't want to apply
    # if col == 'col_name':
        #continue
    df[col] = df[col].fillna(df[col].median())
    
# categorical
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].fillna('unknown')

print( df.isnull().sum()[df.isnull().sum()>0] )

Series([], dtype: int64)

In [60]:
# standardize messy text columns
for col in df.select_dtypes(include="object").columns:
    df[col] = (df[col]
               .str.strip()
               .str.lower()
               .str.replace(r'\s+', ' ', regex=True)  # collapse internal double spaces
               )

df.select_dtypes(include="object").apply(lambda s: s.unique())

fullname            [maria khan, lucas wang, liam johnson, liam na...
email               [maria.khan@example.com, lucas.wang@example.co...
signup_date         [14/12/2023, june 13, 2023, 05/07/2024, july 1...
country             [india, usa, australia, united kingdom, unknow...
order_date          [22-apr-2023, 03/08/2024, 07/08/2023, 11/06/20...
product_category    [clothin, home & garden, sports, unknown, clot...
price               [unknown, $142.55, $451.71, $492.01, -$416.13,...
payment_method      [paypal, debit card, credit card, bank transfe...
dtype: object

In [61]:
# mapping dicts to standardize messy category values (give a snippet to ai so it generates the dicts)
country_map = {
    'u.k.': 'united kingdom',
    'uk': 'united kingdom',
}

product_category_map = {
    'clothin': 'clothing',
    'cloths': 'clothing',
    'electronic': 'electronics',
    'electronicss': 'electronics',
}

payment_method_map = {
    'banktransfer': 'bank transfer',
}

df['country'] = df['country'].replace(country_map)
df['product_category'] = df['product_category'].replace(product_category_map)
df['payment_method'] = df['payment_method'].replace(payment_method_map)

#or
#df['country'] = df['country'].map(country_map).fillna(df['country'])
#df['product_category'] = df['product_category'].map(product_category_map).fillna(df['product_category'])
#df['payment_method'] = df['payment_method'].map(payment_method_map).fillna(df['payment_method'])

print(sorted(df['country'].unique()))
print(sorted(df['product_category'].unique()))
print(sorted(df['payment_method'].unique()))
print(df.head(10))

['australia', 'brazil', 'canada', 'france', 'germany', 'india', 'japan', 'mexico', 'united kingdom', 'unknown', 'usa']
['books', 'clothing', 'electronics', 'home & garden', 'sports', 'toys', 'unknown']
['bank transfer', 'credit card', 'debit card', 'paypal', 'unknown']
   customer_id       fullname                      email      signup_date  \
0           19     maria khan     maria.khan@example.com       14/12/2023
1            3     lucas wang     lucas.wang@example.com    june 13, 2023
2           21   liam johnson   liam.johnson@example.com       05/07/2024
3           28  liam nakamura  liam.nakamura@example.com    july 10, 2024
4           46   chloe dubois   chloe.dubois@example.com       09/19/2024
5           33  noah nakamura  noah.nakamura@example.com  august 04, 2023
6           34      wei patel      wei.patel@example.com       26/01/2023
7           51  sofia ibrahim  sofia.ibrahim@example.com       06/19/2023
8           44   mohammed kim   mohammed.kim@example.com       21/05/2024
9           18  mohammed wang  mohammed.wang@example.com   april 29, 2024

          country    age   order_date product_category     price  quantity  \
0           india   21.0  22-apr-2023         clothing   unknown       3.0
1             usa   35.0   03/08/2024    home & garden   $142.55       4.0
2       australia  999.0   07/08/2023           sports   $451.71       3.0
3  united kingdom   36.0   11/06/2023          unknown   $492.01       9.0
4       australia   66.0   31/05/2024           sports  -$416.13       9.0
5             usa   40.0   11/29/2024         clothing   $180.07       9.0
6         unknown   28.0  03-jul-2023             toys   $462.62       7.0
7         unknown   49.0   23/04/2024         clothing   $269.39       7.0
8           india   40.0  14-feb-2024         clothing   $446.87       2.0
9         germany   48.0   02/21/2024         clothing   $180.38       7.0

  payment_method  rating
0         paypal     2.9
1     debit card     1.4
2     debit card     1.0
3    credit card     3.1
4  bank transfer     4.6
5     debit card     4.9
6         paypal     2.1
7    credit card     1.3
8     debit card     1.9
9  bank transfer     4.5

In [62]:
# $ , ; .

#remove characteres in text 
df['price'] = (
    df['price']
    .astype(str)
    .str.replace( r'[$£,]', '', regex=True )
    .str.strip()
) 

# convert to correct dtype
df['price'] = pd.to_numeric(df['price'], errors='coerce')

df['price'].sample(10)

24    322.53
65    339.23
26    246.86
17       NaN
39    197.79
67    194.60
15     84.98
0        NaN
13    178.23
20    453.14
Name: price, dtype: float64

# if we had mixed bool values use a mapping dict, example:

bool_map = {
    'yes': True, 
    'y': True, 
    'true': True, 
    '1': True,
    'no': False, 
    'n': False, 
    'false': False, 
    '0': False,
}

df['col'] = df['col'].replace(bool_map)

In [63]:
# handling dates

date_cols = ['signup_date', 'order_date']
#or
# date_cols = [c for c in df.columns if 'date' in c]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], dayfirst=False, format='mixed', errors='coerce')
    
failed = df[['signup_date', 'order_date']].isnull().sum()
print(failed)
df.sample(10)

signup_date    0
order_date     0
dtype: int64

,customer_id,fullname,email,signup_date,country,age,order_date,product_category,price,quantity,payment_method,rating
66,26,emma dubois,emma.dubois@example.com,2024-02-10,france,33.0,2023-05-15,toys,324.52,8.0,debit card,4.7
30,2,maria smith,maria.smith@example.com,2023-08-27,germany,23.0,2024-06-01,books,18.14,4.0,bank transfer,2.7
60,11,anna smith,anna.smith@example.com,2024-07-03,canada,40.0,2023-01-10,toys,173.39,5.0,debit card,1.6
37,54,liam kim,liam.kim@example.com,2023-06-06,mexico,19.0,2023-09-02,clothing,61.62,6.0,bank transfer,3.8
27,23,noah kim,noah.kim@example.com,2024-07-09,mexico,21.0,2023-03-04,toys,-160.23,1.0,bank transfer,3.0
0,19,maria khan,maria.khan@example.com,2023-12-14,india,21.0,2023-04-22,clothing,NaN,3.0,paypal,2.9
20,30,emma dubois,emma.dubois@example.com,2024-06-01,france,-31.0,2024-05-15,home & garden,453.14,1.0,credit card,3.5
28,32,anna smith,anna.smith@example.com,2023-06-02,canada,25.0,2024-07-12,electronics,293.34,3.0,debit card,1.5
44,6,aisha kowalski,aisha.kowalski@example.com,2024-10-12,australia,35.0,2024-09-01,clothing,108.71,5.0,unknown,3.4
59,47,fatima nguyen,fatima.nguyen@example.com,2024-10-14,germany,34.0,2023-10-11,books,244.88,4.0,paypal,2.8

In [66]:
# extract year, month, day
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_day_of_week'] = df['order_date'].dt.day_name()

df[['order_date', 'order_year', 'order_month', 'order_day_of_week']]

   order_date  order_year  order_month order_day_of_week
0  2023-04-22        2023            4          Saturday
1  2024-03-08        2024            3            Friday
2  2023-07-08        2023            7          Saturday
3  2023-11-06        2023           11            Monday
4  2024-05-31        2024            5            Friday
..        ...         ...          ...               ...
63 2024-09-13        2024            9            Friday
64 2024-03-19        2024            3           Tuesday
65 2023-07-10        2023            7            Monday
66 2023-05-15        2023            5            Monday
67 2024-07-07        2024            7            Sunday

[63 rows x 4 columns]

In [ ]:
# apply logic tests
# flag rows that fail plausibility / consistency checks instead of silently altering data

df['age_valid'] = df['age'].between(0, 120)
df['rating_valid'] = df['rating'].between(1, 5)
df['price_valid'] = df['price'] >= 0
df['date_order_valid'] = df['order_date'] >= df['signup_date']
df['email_valid'] = df['email'].str.match(r'^[^@\s]+@[^@\s]+\.[^@\s]+$')

checks = ['age_valid', 'rating_valid', 'price_valid', 'date_order_valid', 'email_valid']
print(df[checks].sum())

print()

print("rows failing at least one check:", (~df[checks].all(axis=1)).sum())

df[~df[checks].all(axis=1)]

age_valid           56
rating_valid        61
price_valid         58
date_order_valid    28
email_valid         63
dtype: int64

rows failing at least one check: 41

,customer_id,fullname,email,signup_date,country,age,order_date,product_category,price,quantity,payment_method,rating,order_year,order_month,order_day_of_week,age_valid,rating_valid,price_valid,date_order_valid,email_valid
0,19,maria khan,maria.khan@example.com,2023-12-14,india,21.0,2023-04-22,clothing,NaN,3.0,paypal,2.9,2023,4,Saturday,True,True,False,False,True
2,21,liam johnson,liam.johnson@example.com,2024-05-07,australia,999.0,2023-07-08,sports,451.71,3.0,debit card,1.0,2023,7,Saturday,False,True,True,False,True
3,28,liam nakamura,liam.nakamura@example.com,2024-07-10,united kingdom,36.0,2023-11-06,unknown,492.01,9.0,credit card,3.1,2023,11,Monday,True,True,True,False,True
4,46,chloe dubois,chloe.dubois@example.com,2024-09-19,australia,66.0,2024-05-31,sports,-416.13,9.0,bank transfer,4.6,2024,5,Friday,True,True,False,False,True
8,44,mohammed kim,mohammed.kim@example.com,2024-05-21,india,40.0,2024-02-14,clothing,446.87,2.0,debit card,1.9,2024,2,Wednesday,True,True,True,False,True
9,18,mohammed wang,mohammed.wang@example.com,2024-04-29,germany,48.0,2024-02-21,clothing,180.38,7.0,bank transfer,4.5,2024,2,Wednesday,True,True,True,False,True
11,16,yuki nakamura,yuki.nakamura@example.com,2024-04-07,japan,46.0,2023-04-05,clothing,15.41,9.0,paypal,3.4,2023,4,Wednesday,True,True,True,False,True
12,14,noah patel,noah.patel@example.com,2024-03-08,germany,21.0,2023-03-22,electronics,408.93,9.0,credit card,3.1,2023,3,Wednesday,True,True,True,False,True
14,29,anna müller,anna.müller@example.com,2023-05-18,canada,60.0,2023-09-28,electronics,372.50,3.0,paypal,12.0,2023,9,Thursday,True,False,True,True,True
17,38,david khan,david.khan@example.com,2023-07-14,mexico,42.0,2023-09-18,electronics,NaN,9.0,paypal,2.5,2023,9,Monday,True,True,False,True,True
18,21,liam johnson,liam.johnson@example.com,2024-05-07,australia,999.0,2023-07-08,sports,451.71,3.0,debit card,1.0,2023,7,Saturday,False,True,True,False,True
19,40,olivia kowalski,olivia.kowalski@example.com,2024-07-21,france,62.0,2023-05-11,clothing,470.48,3.0,paypal,2.6,2023,5,Thursday,True,True,True,False,True
20,30,emma dubois,emma.dubois@example.com,2024-06-01,france,-31.0,2024-05-15,home & garden,453.14,1.0,credit card,3.5,2024,5,Wednesday,False,True,True,False,True
21,42,emma lopez,emma.lopez@example.com,2023-10-18,united kingdom,999.0,2024-06-11,toys,318.31,6.0,credit card,3.1,2024,6,Tuesday,False,True,True,True,True
22,37,james khan,james.khan@example.com,2023-09-29,united kingdom,34.0,2023-02-09,electronics,176.12,6.0,debit card,3.4,2023,2,Thursday,True,True,True,False,True
23,11,anna smith,anna.smith@example.com,2024-07-03,canada,40.0,2023-01-10,toys,173.39,5.0,debit card,1.6,2023,1,Tuesday,True,True,True,False,True
25,52,priya silva,priya.silva@example.com,2023-12-02,united kingdom,47.0,2023-08-05,sports,166.79,7.0,paypal,4.0,2023,8,Saturday,True,True,True,False,True
27,23,noah kim,noah.kim@example.com,2024-07-09,mexico,21.0,2023-03-04,toys,-160.23,1.0,bank transfer,3.0,2023,3,Saturday,True,True,False,False,True
29,59,david rossi,david.rossi@example.com,2024-10-05,japan,57.0,2024-04-21,sports,413.74,10.0,unknown,2.3,2024,4,Sunday,True,True,True,False,True
31,17,james chen,james.chen@example.com,2023-12-05,unknown,63.0,2023-03-14,unknown,122.81,8.0,paypal,3.2,2023,3,Tuesday,True,True,True,False,True
32,60,liam chen,liam.chen@example.com,2023-09-07,australia,-35.0,2024-04-20,books,307.11,7.0,debit card,1.1,2024,4,Saturday,False,True,True,True,True
33,57,noah costa,noah.costa@example.com,2024-08-02,unknown,69.0,2023-02-12,home & garden,NaN,6.0,credit card,3.0,2023,2,Sunday,True,True,False,False,True
34,4,yuki khan,yuki.khan@example.com,2024-10-09,brazil,40.0,2023-09-28,electronics,270.43,7.0,credit card,3.2,2023,9,Thursday,True,True,True,False,True
39,49,priya dubois,priya.dubois@example.com,2024-01-03,australia,52.0,2023-03-05,clothing,197.79,10.0,credit card,4.4,2023,3,Sunday,True,True,True,False,True
40,10,john garcia,john.garcia@example.com,2024-11-27,united kingdom,25.0,2024-03-08,books,36.45,7.0,bank transfer,3.1,2024,3,Friday,True,True,True,False,True
41,35,aisha kowalski,aisha.kowalski@example.com,2023-08-16,australia,20.0,2023-07-24,sports,178.08,4.0,paypal,1.1,2023,7,Monday,True,True,True,False,True
44,6,aisha kowalski,aisha.kowalski@example.com,2024-10-12,australia,35.0,2024-09-01,clothing,108.71,5.0,unknown,3.4,2024,9,Sunday,True,True,True,False,True
46,20,john nguyen,john.nguyen@example.com,2023-04-11,japan,69.0,2023-02-21,toys,499.64,1.0,credit card,4.7,2023,2,Tuesday,True,True,True,False,True
49,1,aisha smith,aisha.smith@example.com,2023-09-08,france,65.0,2023-08-17,clothing,339.97,9.0,credit card,3.4,2023,8,Thursday,True,True,True,False,True
50,45,david nguyen,david.nguyen@example.com,2023-09-13,japan,-21.0,2023-05-05,sports,71.00,8.0,bank transfer,5.0,2023,5,Friday,False,True,True,False,True
51,8,maria patel,maria.patel@example.com,2024-02-15,usa,70.0,2023-10-02,electronics,110.25,8.0,debit card,4.5,2023,10,Monday,True,True,True,False,True
53,5,chloe nakamura,chloe.nakamura@example.com,2023-03-13,germany,54.0,2023-02-16,toys,117.81,5.0,credit card,4.4,2023,2,Thursday,True,True,True,False,True
54,39,john dubois,john.dubois@example.com,2024-10-11,unknown,57.0,2023-05-08,toys,450.52,9.0,paypal,3.7,2023,5,Monday,True,True,True,False,True
57,27,john smith,john.smith@example.com,2024-07-30,mexico,47.0,2023-04-13,electronics,255.41,6.0,debit card,4.5,2023,4,Thursday,True,True,True,False,True
58,43,liam müller,liam.müller@example.com,2023-05-31,germany,32.0,2023-01-26,electronics,307.58,2.0,bank transfer,2.7,2023,1,Thursday,True,True,True,False,True
59,47,fatima nguyen,fatima.nguyen@example.com,2024-10-14,germany,34.0,2023-10-11,books,244.88,4.0,paypal,2.8,2023,10,Wednesday,True,True,True,False,True
60,11,anna smith,anna.smith@example.com,2024-07-03,canada,40.0,2023-01-10,toys,173.39,5.0,debit card,1.6,2023,1,Tuesday,True,True,True,False,True
61,9,lucas silva,lucas.silva@example.com,2024-08-21,united kingdom,34.0,2024-03-14,books,202.70,4.0,credit card,3.0,2024,3,Thursday,True,True,True,False,True
63,15,fatima ali,fatima.ali@example.com,2024-06-24,france,-28.0,2024-09-13,sports,482.36,9.0,paypal,3.9,2024,9,Friday,False,True,True,True,True
64,58,olivia smith,olivia.smith@example.com,2023-04-19,australia,44.0,2024-03-19,home & garden,319.61,8.0,credit card,12.0,2024,3,Tuesday,True,False,True,True,True
66,26,emma dubois,emma.dubois@example.com,2024-02-10,france,33.0,2023-05-15,toys,324.52,8.0,debit card,4.7,2023,5,Monday,True,True,True,False,True

1. df[checks] — selects just the 5 boolean flag columns (age_valid, rating_valid, price_valid, date_order_valid, email_valid), giving a mini DataFrame of True/False values, one row per original row.

2. .all(axis=1) — for each row, checks whether all values across those columns are True. 
axis=1 means "collapse across columns, row-wise" (as opposed to axis=0, which would collapse down each column). 
Result: one boolean per row — True only if that row passed every check.

3. ~ — negates it, flipping True↔False. 
Now it's True for rows that failed at least one check (since "not all passed" = "at least one failed").

4. df[...] — boolean-indexes the full DataFrame with that mask, keeping only the rows that failed something.

So the whole line reads as: "give me every row where at least one of the five validity checks came back False."